spring:
  application:
    name: standard-cloud-admin
  profiles.active: dev
  datasource:
    url: jdbc:mysql://${jdbc.hostName}:${jdbc.hostPort}/${jdbc.dbName}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: ${jdbc.userName}
    password: ${jdbc.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  data:
    mongodb:
      uri: mongodb://${mongodb.hostName}:${mongodb.hostPort}/${mongodb.dbName}
      option:
        min-connection-per-host: 0
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 12000
        max-connection-idle-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-connect-timeout: 20000
        heartbeat-socket-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 1000
        local-threshold: 15

mybatis:
  mapperLocations: classpath*:mapper/*.xml

