jdbc:
  hostName: 127.0.0.1
  hostPort: 3306
  dbName: standard_cloud
  userName: root
  password: 123456

mongodb:
  hostName: localhost
  hostPort: 27017
  dbName: standard_cloud_v2
  userName:
  password:

log.path: logs
upload.path: upload

server:
  context-path: /
  port: 8082