jdbc:
  hostName: 127.0.0.1
  hostPort: 3306
  dbName: standard_cloud
  userName: root
  password: 123456

mongo:
  hostName: 127.0.0.1
  hostPort: 27017
  dbName: standard_cloud_v2
  userName:
  password:

log.path: logs
upload.path: upload

server:
  context-path: /
  port: 8081
  tomcat:
    basedir: tomcat
    accesslog:
      enabled: true
      directory: ${log.path}/tomcat
      request-attributes-enabled: true
      pattern: '%t [%I] %{X-Forwarded-For}i %a %r %s %b (%D ms)'
      buffered: true